#!/bin/bash
#
# Prepara un sistema operativo GNU/Linux basado en Debian
# Crea .ISO

#Inicializar variables
VER=1.0
BASE=buster
ARCH=amd64
ROOT=sistema
FILE=instalar.sh
USER=riotec
#Donde diga image deberá ir arranque

# Colores
rojo='\e[1;31m'
blanco='\e[1;37m'
amarillo='\e[1;33m'
apagado='\e[0m'

# TITULO
echo -e "\n$apagado---------------------------"
echo -e "$blanco   CREARTE ISO$apagado"
echo -e "       Version $VER"
echo -e "---------------------------\n"

# Check: Debe ser root
if [ "$EUID" -ne 0 ]
	then echo -e "$rojo* ERROR: Debe ejecutarse como root.$apagado\n"
	exit
fi

# pwd sin espacios
WD=`pwd`
if [[ $WD == *" "* ]]
	then echo -e "$rojo* ERROR: hay espacios en la ruta actual.$apagado\n"
	exit
fi

# Action for "clean"
ACTION=$1
if [ "$ACTION" == "clean" ]; then
	rm -rf {arranque,$ROOT,*.iso}
	echo -e "$amarillo* Todo limpio!$apagado\n"
	exit
fi

# Actions for build (default) and "cambios"
if [ "$ACTION" != "cambios" ]; then
	# Prepare debootstrap host environment
	echo -e "$amarillo* Armando de cero.$apagado"
	rm -rf {arranque,$ROOT,*.iso}
	CACHE=debootstrap-$BASE-$ARCH.tar.gz
	if [ -f "$CACHE" ]; then
		echo -e "$amarillo* $CACHE existe, extrayendo existing archive...$apagado"
		sleep 2
		tar zxvf $CACHE
	else 
		echo -e "$amarillo* $CACHE no existe, corriendo debootstrap...$apagado"
		sleep 2
		apt-get install debootstrap squashfs-tools grub-pc-bin \
			mtools grub-efi-amd64-bin syslinux \
			syslinux-common isolinux xorriso syslinux-efi memtest86+
		rm -rf $ROOT; mkdir -p $ROOT
		debootstrap --arch=$ARCH --variant=minbase $BASE $ROOT
		tar zcvf $CACHE ./$ROOT	
	fi
else
	# Enter existing system shell to make cambios
	echo -e "$amarillo* Actualizando existing arranque.$apagado"
fi

# Configurando el instalar.sh script (ALL): Base configuration
cat > $ROOT/$FILE <<EOL
#!/bin/bash
# System mounts
mount none -t proc /proc;
mount none -t sysfs /sys;
mount none -t devpts /dev/pts
# Set hostname
echo 'riotec' > /etc/hostname
echo 'riotec' > /etc/debian_chroot
# Set hosts
cat > /etc/hosts <<END
127.0.0.1	localhost
127.0.1.1	riotec
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
END
# Set default locale
cat >> /etc/bash.bashrc <<END
export LANG="C"
export LC_ALL="C"
END
# Export environment
export HOME=/root; export LANG=C; export LC_ALL=C;
EOL

# Setup script (BUILD): Install packages
if [ "$ACTION" != "cambios" ]; then
if [ "$ARCH" == "i386" ]; then
	KERN="686"
else
	KERN="amd64"
fi
if [ "$BASE" == "buster" ]; then
	# Buster usa PHP 7.3 and needs extra Chromium packages
	PHPV="7.3"
	PKGS="chromium-common chromium-sandbox"
else
	# Stretch uses PHP 7.0
	PHPV="7.0"
	PKGS=""
fi
cat >> $ROOT/$FILE <<EOL
# Install packages
export DEBIAN_FRONTEND=noninteractive
apt install --no-install-recommends --yes \
	linux-image-$KERN live-boot systemd-sysv firmware-linux-free vim-tiny \
	xserver-xorg x11-xserver-utils xinit xterm openbox obconf obmenu sudo \
	plymouth plymouth-themes compton libnotify-bin xfce4-notifyd beep wget \
	xfce4-power-manager gir1.2-notify-0.7 laptop-detect pm-utils dbus-x11 \
	network-manager-gnome fonts-lato xfce4-appfinder x11vnc pwgen slim \
	tint2 nitrogen gtk-theme-switch gtk2-engines numix-gtk-theme xvkbd \
	gpicview mousepad lxappearance lxmenu-data lxrandr lxterminal volti \
	pcmanfm libfm-modules os-prober discover hdparm smartmontools lvm2 \
	gparted gnome-disk-utility gsettings-desktop-schemas baobab gddrescue \
	lshw-gtk testdisk curlftpfs nmap cifs-utils time openssh-client rsync \
	f2fs-tools reiserfsprogs dosfstools ntfs-3g hfsutils reiser4progs \
	sshfs jfsutils smbclient partclone iputils-ping net-tools yad pigz \
	nfs-common nginx php-fpm php-cli iptables-persistent openssh-server \
	nano wireless-tools wpagui curl dialog locales mdadm chromium $PKGS
# Set vi editor preferences
perl -p -i -e 's/^set compatible$/set nocompatible/g' /etc/vim/vimrc.tiny
# Use local RTC in Linux (via /etc/adjtime) and disable network time updates
systemctl disable systemd-timesyncd.service
# Disable SSH server and delete keys
systemctl disable ssh
rm -f /etc/ssh/ssh_host_*
# Prevent chromium "save password" prompts
mkdir -p /etc/chromium/policies/managed
cat > /etc/chromium/policies/managed/no-password-management.json <<END
{
    "AutoFillEnabled": false,
    "PasswordManagerEnabled": false
}
END
# Add regular user
useradd --create-home $USER --shell /bin/bash
adduser $USER sudo
echo '$USER:$USER' | chpasswd
# Prepare single-user system
echo 'root:$USER' | chpasswd
echo 'default_user root' >> /etc/slim.conf
echo 'auto_login yes' >> /etc/slim.conf
echo "Setting default plymouth theme..."
plymouth-set-default-theme -R riotec
update-initramfs -u
ln -s /usr/bin/pcmanfm /usr/bin/nautilus
# Configure nginx/php-fpm application server
perl -p -i -e 's/^user = .*$/user = root/g' /etc/php/$PHPV/fpm/pool.d/www.conf
perl -p -i -e 's/^group = .*$/group = root/g' /etc/php/$PHPV/fpm/pool.d/www.conf
perl -p -i -e 's/^ExecStart=(.*)$/ExecStart=\$1 -R/g' /lib/systemd/system/php$PHPV-fpm.service
cat > /etc/nginx/sites-available/riotec <<'END'
server {
	listen		80 default_server;
	server_name	localhost;
	root		/var/www/html;
	index		index.php;
	location ~* \.php$ {
		fastcgi_pass	unix:/run/php/php$PHPV-fpm.sock;
		include		fastcgi_params;
		fastcgi_param	SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
		fastcgi_param	SCRIPT_NAME \$fastcgi_script_name;
	}
}
END
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/riotec /etc/nginx/sites-enabled/
# Save space
rm -f /usr/bin/{rpcclient,smbcacls,smbclient,smbcquotas,smbget,smbspool,smbtar}
rm -f /usr/share/icons/*/icon-theme.cache
rm -rf /usr/share/doc
rm -rf /usr/share/man
EOL
fi

# Setup script: (UPDATE) Open shell to make cambios
if [ "$ACTION" == "cambios" ]; then
cat >> $ROOT/$FILE << EOL
echo -e "$rojo>>> Abriendo interactive shell. Type 'exit' when termines de hacer cambios.$apagado"
echo
bash
EOL
fi

# Instalar.sh Setup script: (ALL) limpiar and salir
cat >> $ROOT/$FILE <<EOL
# Clean up and exit
apt-get autoremove && apt-get clean
rm -rf /var/lib/dbus/machine-id
rm -rf /tmp/*
rm -f /etc/resolv.conf
rm -f /etc/debian_chroot
rm -rf /var/lib/apt/lists/????????*
umount -lf /proc;
umount /sys;
umount /dev/pts
exit
EOL

# Copy plymouth theme before running instalar.sh script
echo -e "$amarillo* Copying assets to root directorio...$apagado"
rsync -h --info=progress2 --archive \
	./solenoide/$ROOT/usr/share/* \
	./$ROOT/usr/share/

# Copy /etc/resolv.conf before running instalar.sh script
cp /etc/resolv.conf ./$ROOT/etc/

# Run instalar.sh script inside chroot
chmod +x $ROOT/$FILE
echo
echo -e "$rojo>>> ENTERING CHROOT SYSTEM$apagado"
echo
sleep 2
chroot $ROOT/ /bin/bash -c "./$FILE"
echo
echo -e "$rojo>>> EXITED CHROOT SYSTEM$apagado"
echo
sleep 2
rm -f $ROOT/$FILE

# Preparar arranque
echo -e "$amarillo* Preparando imagen...$apagado"
rm -f $ROOT/root/.bash_history
rm -rf arranque riotec-$VER.iso
mkdir -p arranque/{live,isolinux,EFI/boot,boot/grub/x86_64-efi,tmp}
cp $ROOT/boot/vmlinuz* arranque/live/vmlinuz
cp $ROOT/boot/initrd* arranque/live/initrd
cp /boot/memtest86+.bin arranque/live/memtest
cp /usr/lib/ISOLINUX/isolinux.bin arranque/isolinux/
cp /usr/lib/syslinux/modules/bios/menu.c32 arranque/isolinux/
cp /usr/lib/syslinux/modules/bios/vesamenu.c32 arranque/isolinux/
cp /usr/lib/syslinux/modules/bios/hdt.c32 arranque/isolinux/
cp /usr/lib/syslinux/modules/bios/ldlinux.c32 arranque/isolinux/
cp /usr/lib/syslinux/modules/bios/libutil.c32 arranque/isolinux/
cp /usr/lib/syslinux/modules/bios/libmenu.c32 arranque/isolinux/
cp /usr/lib/syslinux/modules/bios/libcom32.c32 arranque/isolinux/
cp /usr/lib/syslinux/modules/bios/libgpl.c32 arranque/isolinux/
cp /usr/share/misc/pci.ids arranque/isolinux/
# =====================================
cp /home/nico/grub.cfg arranque/boot/grub/grub.cfg
cp /home/nico/grub-standalone.cfg arranque/tmp/grub-standalone.cfg
cp /home/nico/RIOTEC_LIVE arranque/RIOTEC_LIVE
cp -r /usr/lib/grub/x86_64-efi/* arranque/boot/grub/x86_64-efi/
grub-mkstandalone --format=x86_64-efi \
	--output=arranque/tmp/bootx64.efi \
	--locales="" --fonts="" \
	"boot/grub/grub.cfg=arranque/tmp/grub-standalone.cfg"
(cd arranque/EFI/boot && \
    dd if=/dev/zero of=efiboot.img bs=1M count=20 && \
    mkfs.vfat efiboot.img && \
    mmd -i efiboot.img efi efi/boot && \
    mcopy -vi efiboot.img arranque/tmp/bootx64.efi ::efi/boot/
)
# =====================================IMPORTANTE: MODIFICAR LINEA DE ARRIBA
# Apply cambios from overlay - solenoide
echo -e "$amarillo* Applying cambios desde solenoide - overlay...$apagado"
rsync -h --info=progress2 --archive \
	./solenoide/* \
	.

# Fix permissions
chroot $ROOT/ /bin/bash -c "chown -R root: /etc /root"
chroot $ROOT/ /bin/bash -c "chown -R www-data: /var/www/html"

# Enable startup of monitor service
chroot $ROOT/ /bin/bash -c "chmod 644 /etc/systemd/system/riotec.service"
chroot $ROOT/ /bin/bash -c "systemctl enable riotec"

# Update version number
perl -p -i -e "s/\\\$VERSION/$VER/g" arranque/isolinux/isolinux.cfg
echo $VER > $ROOT/var/www/html/VERSION

# Compress live filesystem
echo -e "$amarillo* Comprimiendo live filesystem...$apagado"
mksquashfs $ROOT/ arranque/live/filesystem.squashfs -e boot

# Create ISO arranque
echo -e "$amarillo* Creando la ISO...$apagado"
# | xorriso -as mkisofs -r \
# |	-J -joliet-long \
# |	-isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
# |	-partition_offset 16 \
# |	-A "RIOTEC $VER" -volid "RIOTEC $VER" \
# |	-b isolinux/isolinux.bin \
# |	-c isolinux/boot.cat \
# |	-no-emul-boot -boot-load-size 4 -boot-info-table \
# |	-o riotec-$VER.iso \
# |	arranque

# #####################
xorriso -as mkisofs \
    -iso-level 3 \
    -o riotec-$VER.iso \
    -full-iso9660-filenames \
    -A "RIOTEC $VER" -volid "RIOTEC $VER" \
    -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
    -eltorito-boot \
        isolinux/isolinux.bin \
        -no-emul-boot \
        -boot-load-size 4 \
        -boot-info-table \
        --eltorito-catalog isolinux/isolinux.cat \
    -eltorito-alt-boot \
        -e /EFI/boot/efiboot.img \
        -no-emul-boot \
        -isohybrid-gpt-basdat \
    -append_partition 2 0xef arranque/EFI/boot/efiboot.img arranque

# #######################
# Todo listo
echo -e "$amarillo\nISO imagen guardada:"
du -sh riotec-$VER.iso
echo -e "$apagado"
echo
echo "Listo."
echo
